name: CI

on:
  workflow_dispatch:
  push:
    branches: 'main'
  schedule:
    - cron: '0 23 * * *'

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up committer
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    - name: Update
      run: |
        ./update.sh
        git push
